### ISSUE TITLE
RE: check_recipes.ipynb

### ISSUE THREAD

**Issue by palautatan** [palautatan/perfectBananaBread#14]
**TO-DO**
1. Create column to show which recipe the ingredient belongs to
2. Decide how to work with different lengthed recipes -- this would probably have to deal with assigning np.NaN to recipes that do not have a number amount ("cooking oil" is one) -- probably remove cooking oil
3. Clean up lines like 1977 and "cooking oil" -- see how many issues have the (16.3 ounce) package problem

**Comment by sherm17** [comment]
Issue 14, Part 2 and 3
Part 2: Remove ingredients that do not have a number element — need to write a function
Part 3: Create / append function to check for weird lines like 1977
(i.e. download check_recipes.ipynb and banana_bread_df.csv)

**Comment by sherm17** [comment]
Check to see if other lines are like 1977. If not, maybe hardcode it?
