### ISSUE TITLE
create code to find how many pages a search query has

### ISSUE THREAD

**Issue by palautatan** [palautatan/perfectBananaBread#8]
ex: http://allrecipes.com/search/results/?wt=banana%20bread&sort=re&page=2

How many pages total?

**Comment by palautatan** [comment]
When inputting query, you get "5493 recipe results for "banana bread" on the top of the page.

![screen shot 2017-09-19 at 11 08 49 pm](https://user-images.githubusercontent.com/20163246/30629221-8a02fff8-9d8f-11e7-8806-4f3630063be1.png)
So, let's divide that number by the amount of articles on each search page.

We have that 5493 / 30 = 183.1, therefore we have reason to believe there are 184 pages. 

Update: This is true, and we can access each of those pages by following this pattern: http://allrecipes.com/search/results/?wt=banana%20bread&sort=re&page=184#184

**Comment by sherm17** [comment]
We’re going to check title of recipe before saving the links (bananaBread.py)

**Comment by palautatan** [comment]
I don't think it's worth going past page 10 (http://allrecipes.com/search/results/?wt=banana%20bread&sort=re&page=10), but I don't know how we will be able to collect this information for a generalizable model.

**Comment by palautatan** [comment]
--Return to this issue later (2017-09-24)--
